[shell]
program = "/usr/bin/bash"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
opacity = 1

[colors.primary]
#background = '#1e1e1e'
#background = '#000000'
background = '#161718'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black      = '#171421'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

# Bright colors
[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'

[font]
size = 13.5
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold Regular" }
italic = { family = "Iosevka Term", style = "Regular" }
bold_italic = { family = "Iosevka Term", style = "Bold Regular" }

# 0 | @ | $ | { | } | [ | ] | & | # | * | ! | % 
# a b c d e f g h i j k l m n o p q r s t u v w x y z
# 0 1 2 3 4 5 6 7 8 9 

# size = 11.5
# size = 13
# normal = { family = "JetBrains Mono Nerd Font"}
